remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

title: Arun's Tech Insights
description: Practical tutorials and deep-dives on cloud, DevOps, web development, and blockchain by Solution Architect Arun Munaganti.
show_downloads: false
url: "https://arunsai63.github.io"
baseurl: "/blogs"

markdown: kramdown
highlighter: rouge
theme: null # If using remote_theme
exclude: [README.md, Gemfile, Gemfile.lock]

future: true
